name: Build and deploy full-stack application to Azure Web App - Applaii

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up and build Flask backend and React frontend
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install Flask dependencies
        working-directory: Backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install React dependencies and build React app
        working-directory: Frontend
        run: |
          npm install
          npm run build
          cp -r build/* ../Backend/

      - name: Zip artifact for deployment
        working-directory: Backend
        run: zip -r ../release.zip . -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: flask-react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact for deployment job
        uses: actions/download-artifact@v2
        with:
          name: flask-react-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Applaii'
          slot-name: 'Production'
          startup-command: 'gunicorn -b 0.0.0.0:8000 main:app'
